name: Security Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  snyk_security:
    name: Snyk Security Scan
    runs-on: ubuntu-latest
    
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      SNYK_ORG_ID: ${{ secrets.SNYK_ORG_ID }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Install Snyk CLI
        run: |
          curl -Lo snyk https://github.com/snyk/cli/releases/latest/download/snyk-linux
          chmod +x snyk
          sudo mv snyk /usr/local/bin/
      
      - name: Verify Snyk installation
        run: snyk --version

      - name: Snyk Clear Config (logout)
        run: snyk config clear
          
      - name: Configure Snyk organization
        run: snyk config set org='${{ env.SNYK_ORG_ID }}'

      - name: Confirm Snyk Identity
        run: snyk whoami --experimental
          
      - name: Run Snyk monitor (main/master branch only)
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: snyk monitor --detection-depth=10
          
      - name: Skip monitor for non-main/master branch
        if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master'
        run: echo "Skipping monitor for non-main/master branch - no data sent to dashboard"
        
      - name: Test for vulnerabilities
        run: snyk test --detection-depth=10 || true
